# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "1.6.5"

  on_macos do
    on_intel do
      sha256 "72cca07a2b8b8a2244a727d2804a81ebc7080361c2391af502c66456cc438514"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "808dab776d1043d73223dd9f9ef3a6fd3953809391f9cd80038660bb1eaedc65"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0a385038aa625764458faf6ea86de53c9a96f71c6c2bb8e9056d776df66e18d"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfa82810f8207dc792894d9dc7c0868f88db7c898d416dec719aded4c34fcde7"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergon"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required

end
