# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "3e7d342aeb24a259a97a932a48a9388d815a1ed3b32ab77ae981f667e661a588"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d8b99f9f78a5c2f5521997876b9e20fa5ef3f78cc7e49cc2a369a523940b857"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be7d19384c841cd8e17d0d31afede9d7229870202cbc0af65b901245df447552"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "018dcacd8f41269faf78927091e5310a25082c2775c35e3b9290a2d5f6eda761"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergon"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"
  bash_completion "completions/ergon.bash"
  fish_completion "completions/ergon.fish"
  zsh_completion "completions/ergon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergon"]
    end
  end

  # No zap stanza required

end
