# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergon" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "4306ec2a43feaef042d884e2f03ccab1648f7fe7ee0f694c3e2b4ea1c2ee3995"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d8d1d9a14d2e7df4faec7578952369cce8879600eb58b3f8a6a74c73104aeed"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62d846fc65c7011c5ca9055025275a10e50191a12837cf2dbb2364f337c13022"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "abe32365c2aab6e64f431c96c45f9547573eb6efeaa177bd4b28f8709129758f"
      url "https://github.com/thesm-os/ergon/releases/download/v#{version}/ergon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergon"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/ergon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergon"

  # No zap stanza required

end
