# This file was generated by GoReleaser. DO NOT EDIT.
cask "techne" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "8595d0ba3f94479f3f6fccc96b4fac00daaf62c19628b632d52d670ab824df66"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18a25acf7a7bde658a33213fd28660b51054809265006828c67b0f529c280875"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae76c025a36b6a956db86cfe142f9b8c5b6046b7f8e75e58b817cb924addbcc6"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2432a9ceddb179379a06629db6b3fc5d0a17392d0a5d7a7ebcfcff1d81e10fdc"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "techne"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/techne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "techne"
  bash_completion "completions/techne.bash"
  fish_completion "completions/techne.fish"
  zsh_completion "completions/techne.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/techne"]
    end
  end

  # No zap stanza required

end
