# This file was generated by GoReleaser. DO NOT EDIT.
cask "techne" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "edab8413f2a0a6f1eb9823d78f55a570ba4729bc6a73cab3503b5151a1c0b7b0"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4af07a894dc5d8352cbb3e3034e74176275fe3d88b58c91665fd06bcc6680685"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1900aceeed8c047186e95a6b7307fe45b1db88a28653be4b3d0e14c67bc11b5b"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d6b97ed0ad9a6ac98a69d0768e5a4e83a588ef426d4780e564eecf7c44ab908"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "techne"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/techne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "techne"
  generate_completions_from_executable "techne", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/techne"]
    end
  end

  # No zap stanza required

end
