# This file was generated by GoReleaser. DO NOT EDIT.
cask "techne" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "f9c23acadb33223ef506bf52343f074e8379710bd2391a55e0d7e9b95cf1e152"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bf0eee38d3b07db19ae20b53950495c83325e6149ef8f536879abc173709235"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "988f9dc2e3c0a7f8e9263fb39c42b4cf4f12e6d338c83b6de607c6ab81cf14e4"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c8e4198a5ce431a8b8f70c6fe0210f7211ca950b46902872ca787f4fe92cf75"
      url "https://github.com/thesm-os/techne/releases/download/v#{version}/techne_#{version}_linux_arm64.tar.gz"
    end
  end

  name "techne"
  desc "Task runner for Go projects: bootstrap, format, lint, test, bench, release, and a multi-stage check umbrella."
  homepage "https://github.com/thesm-os/techne"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "techne"
  bash_completion "completions/techne.bash"
  fish_completion "completions/techne.fish"
  zsh_completion "completions/techne.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/techne"]
    end
  end

  # No zap stanza required

end
